theory cap_4
imports Main
begin

text \<open>Exercise 4.1. Start from the data type of binary trees defined earlier:
datatype a tree = Tip | Node "a tree" a "a tree"
Define a function set :: a tree \<Rightarrow> a set that returns the elements in a tree
and a function ord :: int tree \<Rightarrow> bool that tests if an int tree is ordered.
Define a function ins that inserts an element into an ordered int tree
while maintaining the order of the tree. If the element is already in the tree,
the same tree should be returned. Prove correctness of ins: set (ins x t) =
{x} \<union> set t and ord t =\<Rightarrow> ord (ins i t)\<close>

datatype 'a tree = Tip | Node "'a tree" 'a "'a tree"

fun set :: "'a tree \<Rightarrow> 'a set" where
"set Tip = {}" |
"set (Node l a r) = set l \<union> {a} \<union> set r"

fun ord :: "int tree \<Rightarrow> bool" where
"ord Tip = True" |
"ord (Node l a r) = ((\<forall>x\<in>set l. x < a) \<and> (\<forall>x\<in>set r. a < x) \<and> ord l \<and> ord r)"

fun ins :: "int \<Rightarrow> int tree \<Rightarrow> int tree" where
"ins i Tip = Node Tip i Tip" |
"ins i (Node l a r) = 
  (if i = a then Node l a r
   else if i < a then Node (ins i l) a r
   else Node l a (ins i r))"

lemma set_ins[simp]: "set (ins x t) = {x} \<union> set t"
by (induction t) auto

lemma ord_ins: "ord t \<Longrightarrow> ord (ins i t)"
by (induction t) auto



text \<open>Exercise 4.2. Formalize the following definition of palindromes
• The empty list and a singleton list are palindromes.
• If xs is a palindrome, so is a # xs @ [a].
as an inductive predicate palindrome :: a list \<Rightarrow> bool and prove that rev xs
= xs if xs is a palindrome.\<close>

inductive palindrome :: "'a list \<Rightarrow> bool" where
pal_Nil: "palindrome []" |
pal_One: "palindrome [a]" |
pal_Step: "palindrome xs \<Longrightarrow> palindrome (a # xs @ [a])"

lemma "palindrome xs \<Longrightarrow> rev xs = xs"
by (induction rule: palindrome.induct) auto



text \<open>Exercise 4.3. We could also have defined star as follows:
inductive star :: "(a \<Rightarrow> a \<Rightarrow> bool) \<Rightarrow> a \<Rightarrow> a \<Rightarrow> bool" for r where
refl : "star r x x" |
step : "star r x y =\<Rightarrow> r y z =\<Rightarrow> star r x z"
The single r step is performed after rather than before the star steps. Prove
star r x y =\<Rightarrow> star r x y and star r x y =\<Rightarrow> star r x y. You may need
lemmas. Note that rule induction fails if the assumption about the inductive
predicate is not the first assumption.\<close>

inductive star :: "('a \<Rightarrow> 'a \<Rightarrow> bool) \<Rightarrow> 'a \<Rightarrow> 'a \<Rightarrow> bool" for r where
refl: "star r x x" |
step: "r x y \<Longrightarrow> star r y z \<Longrightarrow> star r x z"

inductive star' :: "('a \<Rightarrow> 'a \<Rightarrow> bool) \<Rightarrow> 'a \<Rightarrow> 'a \<Rightarrow> bool" for r where
refl': "star' r x x" |
step': "star' r x y \<Longrightarrow> r y z \<Longrightarrow> star' r x z"

lemma star'_step: "star' r y z \<Longrightarrow> r x y \<Longrightarrow> star' r x z"
by (induction rule: star'.induct) (auto intro: star'.intros)

lemma star_star': "star r x y \<Longrightarrow> star' r x y"
by (induction rule: star.induct) (auto intro: star'.intros star'_step)

lemma star_step': "star r x y \<Longrightarrow> r y z \<Longrightarrow> star r x z"
by (induction rule: star.induct) (auto intro: star.intros)

lemma star'_star: "star' r x y \<Longrightarrow> star r x y"
by (induction rule: star'.induct) (auto intro: star.intros star_step')



text \<open>Exercise 4.4. Analogous to star, give an inductive definition of the n-fold
iteration of a relation r: iter r n x y should hold if there are x0, ..., xn such
that x = x0, xn = y and r xi xi+1 for all i < n. Correct and prove the
following claim: star r x y =\<Rightarrow> iter r n x y.\<close>

inductive iter :: "('a \<Rightarrow> 'a \<Rightarrow> bool) \<Rightarrow> nat \<Rightarrow> 'a \<Rightarrow> 'a \<Rightarrow> bool" for r where
iter_0: "iter r 0 x x" |
iter_Suc: "r x y \<Longrightarrow> iter r n y z \<Longrightarrow> iter r (Suc n) x z"

lemma star_iter: "star r x y \<Longrightarrow> \<exists>n. iter r n x y"
proof (induction rule: star.induct)
  case (refl x)
  have "iter r 0 x x" by (rule iter_0)
  thus ?case by blast
next
  case (step x y z)
  then obtain n where "iter r n y z" by blast
  with `r x y` have "iter r (Suc n) x z" by (rule iter_Suc)
  thus ?case by blast
qed



text \<open>Exercise 4.5. A context-free grammar can be seen as an inductive definition
where each nonterminal A is an inductively defined predicate on lists of ter
minal symbols: A(w) means that w is in the language generated by A. For
example, the production S \<rightarrow> aSb can be viewed as the implication S w =\<Rightarrow>
S (a # w @[b]) where a and b are terminal symbols, i.e., elements of some
alphabet. The alphabet can be defined like this: datatype alpha = a | b | ...
Define the two grammars (where \<epsilon> is the empty word)
S \<rightarrow> \<epsilon> | aSb | SS
T \<rightarrow> \<epsilon> | TaTb
as two inductive predicates. If you think of a and b as “(” and “)”, the
grammars define balanced strings of parentheses. Prove T w =\<Rightarrow> S w and
S w =\<Rightarrow> Tw separately and conclude S w = T w.
4 Logic and Proof Beyond Equality\<close>

datatype alpha = a | b

inductive S :: "alpha list \<Rightarrow> bool" where
S_emp: "S []" |
S_aSb: "S w \<Longrightarrow> S (a # w @ [b])" |
S_SS:  "S w1 \<Longrightarrow> S w2 \<Longrightarrow> S (w1 @ w2)"

inductive T :: "alpha list \<Rightarrow> bool" where
T_emp: "T []" |
T_TaTb: "T w1 \<Longrightarrow> T w2 \<Longrightarrow> T (w1 @ a # w2 @ [b])"

lemma T_S: "T w \<Longrightarrow> S w"
proof (induction rule: T.induct)
  case T_emp
  show ?case by (rule S_emp)
next
  case (T_TaTb w1 w2)
  from T_TaTb.IH(2) have "S (a # w2 @ [b])" by (rule S_aSb)
  with T_TaTb.IH(1) have "S (w1 @ (a # w2 @ [b]))" by (rule S_SS)
  thus ?case by simp
qed

lemma T_append:
  assumes "T w1" "T w2"
  shows "T (w1 @ w2)"
using assms(2) assms(1)
proof (induction rule: T.induct)
  case T_emp
  thus ?case by simp
next
  case (T_TaTb u v)
  have "w1 @ (u @ a # v @ [b]) = (w1 @ u) @ a # v @ [b]" by simp
  moreover have "T ((w1 @ u) @ a # v @ [b])"
    using T_TaTb.IH(1) T_TaTb.hyps(2) T_TaTb.prems T.T_TaTb by blast
  ultimately show ?case by simp
qed

lemma S_T: "S w \<Longrightarrow> T w"
proof (induction rule: S.induct)
  case S_emp
  show ?case by (rule T_emp)
next
  case (S_aSb w)
  have "a # w @ [b] = [] @ a # w @ [b]" by simp
  moreover have "T ([] @ a # w @ [b])"
    using S_aSb.IH T_emp T_TaTb by blast
  ultimately show ?case by simp
next
  case (S_SS w1 w2)
  thus ?case using T_append by blast
qed

lemma "S w \<longleftrightarrow> T w"
by (blast intro: S_T T_S)



text \<open>Exercise 4.6. In Section 3.1 we defined a recursive evaluation function aval
:: aexp \<Rightarrow> state \<Rightarrow> val. Define an inductive evaluation predicate aval_rel
:: aexp \<Rightarrow> state \<Rightarrow> val \<Rightarrow> bool and prove that it agrees with the recursive
function: aval_rel a s v =\<Rightarrow> aval a s = v, aval a s = v =\<Rightarrow> aval_rel a s v
and thus aval_rel a s v \<leftarrow>\<rightarrow> aval a s = v\<close>

type_synonym vname = string
type_synonym val = int
type_synonym state = "vname \<Rightarrow> val"

datatype aexp = N int | V vname | Plus aexp aexp

fun aval :: "aexp \<Rightarrow> state \<Rightarrow> val" where
"aval (N n) s = n" |
"aval (V x) s = s x" |
"aval (Plus a1 a2) s = aval a1 s + aval a2 s"

inductive aval_rel2 :: "aexp \<Rightarrow> state \<Rightarrow> val \<Rightarrow> bool" where
aval_N: "aval_rel2 (N n) s n" |
aval_V: "aval_rel2 (V x) s (s x)" |
aval_Plus: "aval_rel2 a1 s v1 \<Longrightarrow> aval_rel2 a2 s v2 \<Longrightarrow> aval_rel2 (Plus a1 a2) s (v1 + v2)"

lemma aval_rel_aval: "aval_rel2 e s v \<Longrightarrow> aval e s = v"
by (induction rule: aval_rel2.induct) auto

lemma aval_aval_rel: "aval e s = v \<Longrightarrow> aval_rel2 e s v"
by (induction e arbitrary: v) (auto intro: aval_rel2.intros)

lemma "aval_rel2 e s v \<longleftrightarrow> aval e s = v"
by (blast intro: aval_rel_aval aval_aval_rel)



text \<open>Exercise 4.7. Consider the stack machine from Chapter 3 and recall the
concept of stack underflow from Exercise 3.10. Define an inductive predicate
ok :: nat \<Rightarrow> instr list \<Rightarrow> nat \<Rightarrow> bool such that ok n is n means that with
any initial stack of length n the instructions is can be executed without stack
underflow and that the final stack has length n . Prove that ok correctly
computes the final stack size
[[ok n is n ; length stk = n]] =\<Rightarrow> length (exec is s stk) = n
and that instruction sequences generated by comp cannot cause stack under
flow: ok n (comp a) ? for some suitable value of ?.\<close>

datatype instr = LOADI val | LOAD vname | ADD

fun exec1 :: "instr \<Rightarrow> state \<Rightarrow> val list \<Rightarrow> val list" where
"exec1 (LOADI n) _ stk = n # stk" |
"exec1 (LOAD x) s stk = s x # stk" |
"exec1 ADD _ (j # i # stk) = (i + j) # stk" |
"exec1 ADD _ stk = stk"

fun exec :: "instr list \<Rightarrow> state \<Rightarrow> val list \<Rightarrow> val list" where
"exec [] _ stk = stk" |
"exec (i#is) s stk = exec is s (exec1 i s stk)"

fun comp :: "aexp \<Rightarrow> instr list" where
"comp (N n) = [LOADI n]" |
"comp (V x) = [LOAD x]" |
"comp (Plus e1 e2) = comp e1 @ comp e2 @ [ADD]"

lemma exec_append[simp]: "exec (is1 @ is2) s stk = exec is2 s (exec is1 s stk)"
  apply(induction is1 arbitrary: stk)
  apply auto
done

inductive ok :: "nat \<Rightarrow> instr list \<Rightarrow> nat \<Rightarrow> bool" where
ok_Nil: "ok n [] n" |
ok_LOADI: "ok (Suc n) is n' \<Longrightarrow> ok n (LOADI v # is) n'" |
ok_LOAD: "ok (Suc n) is n' \<Longrightarrow> ok n (LOAD x # is) n'" |
ok_ADD: "2 \<le> n \<Longrightarrow> ok (n - 1) is n' \<Longrightarrow> ok n (ADD # is) n'"

lemma ok_append[simp]: "ok n is1 n'' \<Longrightarrow> ok n'' is2 n' \<Longrightarrow> ok n (is1 @ is2) n'"
by (induction rule: ok.induct) (auto intro: ok.intros)

lemma stk_2: "2 \<le> length stk \<Longrightarrow> \<exists>x y stk'. stk = x # y # stk'"
proof (cases stk)
  case Nil thus ?thesis using \<open>2 \<le> length stk\<close> by simp
next
  case (Cons x xs)
  thus ?thesis proof (cases xs)
    case Nil thus ?thesis using \<open>2 \<le> length stk\<close> Cons by simp
  next
    case (Cons y ys) thus ?thesis using Cons `stk = x # xs` by blast
  qed
qed

lemma ok_exec_length: "ok n is n' \<Longrightarrow> length stk = n \<Longrightarrow> length (exec is s stk) = n'"
proof (induction arbitrary: stk rule: ok.induct)
  case (ok_Nil n) thus ?case by simp
next
  case (ok_LOADI n is n' v) thus ?case by simp
next
  case (ok_LOAD n is n' x) thus ?case by simp
next
  case (ok_ADD n is n')
  then obtain x y stk' where "stk = x # y # stk'" using stk_2 by blast
  with ok_ADD show ?case by simp
qed

lemma ok_comp: "ok n (comp e) (Suc n)"
proof (induction e arbitrary: n)
  case (N n')
  have "ok (Suc n) [] (Suc n)" by (rule ok_Nil)
  hence "ok n [LOADI n'] (Suc n)" by (rule ok_LOADI)
  thus ?case by simp
next
  case (V x)
  have "ok (Suc n) [] (Suc n)" by (rule ok_Nil)
  hence "ok n [LOAD x] (Suc n)" by (rule ok_LOAD)
  thus ?case by simp
next
  case (Plus a1 a2)
  have "ok n (comp a1) (Suc n)" by (rule Plus.IH)
  moreover have "ok (Suc n) (comp a2) (Suc (Suc n))" by (rule Plus.IH)
  ultimately have "ok n (comp a1 @ comp a2) (Suc (Suc n))" by (rule ok_append)
  moreover have "ok (Suc (Suc n)) [ADD] (Suc n)"
    by (intro ok_ADD ok_Nil) auto
  ultimately have "ok n ((comp a1 @ comp a2) @ [ADD]) (Suc n)"
    by (rule ok_append)
  thus ?case by simp
qed

end